# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        container_name: web
        build:
            context: .
            args:
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - sstore_network
        environment:
            PHP_DISPLAY_ERRORS: 'On'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        depends_on:
            - pgsql
    pgsql:
        container_name: pgsql
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sstore_pgsql:/var/lib/postgresql/data'
        networks:
            - sstore_network
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-q",
                    "-d",
                    "${DB_DATABASE}",
                    "-U",
                    "${DB_USERNAME}"
                ]
            retries: 3
            timeout: 5s
networks:
    sstore_network:
        driver: bridge
volumes:
    sstore_pgsql:
        driver: local
